### ISSUE TITLE
Why is the Preferences a .txt if it's a json

### ISSUE THREAD

**Issue by CestDiego** [markjones112358/dmenu-extended#20]
dmenuExtended_preferences.txt is a json valid file, why does it have a .txt extension? also there are lot's of whitespace.

Thank you for this project, I'm loving it! :D I would also like to know if there is a guide to contribute plugins

**Comment by markjones112358** [comment]
Hi Dlego,
It's a .txt file so that your default text editor is opened to edit the 
file. On some systems I found it would either open with a weird 
application or not open at all, so setting it as a .txt solved this.
The formatting of the file is handled by the parser as write time, but 
in general the whitespace it keeps it more readable since it's designed 
to be read and edited by a human.
SublimeText has a similar preferences system with the same json layout.

No plugin guide at present but the plugins repository 
(https://github.com/markjones112358/dmenu-extended-plugins) has an 
example plug-in to start from.

Hope that helps. Glad you're liking it.

Regards,


Mark Jones
