### ISSUE TITLE
Directly calling cache_build leaves global variable d uninitialized

### ISSUE THREAD

**Issue by marczuo** [markjones112358/dmenu-extended#32]
When following the instruction to create a python script to update the cache file:

    #! /bin/python
    import dmenu_extended
    dmenu_extended.dmenu().cache_build()

Python returns error:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/user/Development/dmenu-extended/dmenu_extended.py", line 952, in cache_build
        plugins = self.plugins_available()
      File "/home/user/Development/dmenu-extended/dmenu_extended.py", line 743, in plugins_available
        plugins = self.get_plugins(True)
      File "/home/user/Development/dmenu-extended/dmenu_extended.py", line 284, in get_plugins
        self.plugins_loaded = load_plugins(self.debug)
      File "/home/user/Development/dmenu-extended/dmenu_extended.py", line 195, in load_plugins
        plugins_loaded[0]['plugin'].launch_args = d.launch_args
    AttributeError: 'NoneType' object has no attribute 'launch_args'

This is due to the fact that, without calling `run()`, the global variable `d` is uninitialized. [I made a quick change to get around this issue](https://github.com/marczuo/dmenu-extended/commit/14c97c74827efc5512a3fc4471f1e575b1915f5a), and it seems to be working so far, however I'm not sure if this'll not create any problems.

**Comment by markjones112358** [comment]
Hi Marczuo,
Thanks for raising that issue so promptly and for coming up with the change you made. 
I decided not pull your change in, but it made it very clear where the problem was so was quite helpful - thank you. As the initialize_d function would only ever be called once I felt that moving the initialisation elsewhere would slightly increase the complexity of the code (e.g., a newcomer may wonder if the plugins are calling it). Instead, I initialise the variable in the global scope which appears to have solved the issue.
Let me know your thoughts,

Mark H. Jones

**Comment by marczuo** [comment]
Yes, it appears to be working well now. I've also created a systemd script to automatically update the cache and an interface to control the script in the program, [which you can see here](https://github.com/markjones112358/dmenu-extended/compare/master...marczuo:master).

**Comment by markjones112358** [comment]
Wow,  that's awesome!
I'm definitely keen to pull in your systemd integration (and putting the 'Open:' prompt into the preferences file).
In your fork you still have the initialize_d function - which isn't called from anywhere anymore (surplus to requirements now?).
Also, if dmenu_extended is run without installing via `sudo python setup.py install` the menu is unable to perform the systemd integration, yet it says that it has been sucessfully enabled. This is due to the required files (.service, .timer) not being put into their target locations. My suggestion would be that if the necessary files aren't in place the menu should not show the integration option. This way it caters for those users who don't trust installing dmenu_extended with sudo.

If you create a pull request, I'll bring those changes in.

**Comment by marczuo** [comment]
Good point, I'll need to check if the systemd scripts are installed before showing the menu options. Also, I suppose if the user chooses to install into home directory (`--user`) then I'll have to put the scripts into the local directory as well.

I'll work on getting these done when I get a chance, and I'll file a pull request when I'm done.

**Comment by markjones112358** [comment]
Nice,  thanks a lot! No rush.
